import NavBar from "@/components/NavBar";
import Header from "../components/Header";
import "./globals.css";

export const metadata = {
  title: "IMDb-clone",
  description: "This is IMDb clone website generated by next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {/* 
        {Search} */}
          <Header />
          <NavBar />
          {children}
      </body>
    </html>
  );
}
