import Header from '../components/Header'
import './globals.css'

export const metadata = {
  title: 'Imdb-clone',
  description: 'This is imdb clone website generated by next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* {NavBar}
        {Search} */}
        <Header />
        {children}
      </body>
    </html>
  );
}
