import './globals.css'

export const metadata = {
  title: 'Imdb-clone',
  description: 'This is imdb clone website generated by next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
